require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ElaborationsController do

  # This should return the minimal set of attributes required to create a valid
  # Elaboration. As you add validations to Elaboration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all elaborations as @elaborations" do
      elaboration = Elaboration.create! valid_attributes
      get :index
      assigns(:elaborations).should eq([elaboration])
    end
  end

  describe "GET show" do
    it "assigns the requested elaboration as @elaboration" do
      elaboration = Elaboration.create! valid_attributes
      get :show, :id => elaboration.id.to_s
      assigns(:elaboration).should eq(elaboration)
    end
  end

  describe "GET new" do
    it "assigns a new elaboration as @elaboration" do
      get :new
      assigns(:elaboration).should be_a_new(Elaboration)
    end
  end

  describe "GET edit" do
    it "assigns the requested elaboration as @elaboration" do
      elaboration = Elaboration.create! valid_attributes
      get :edit, :id => elaboration.id.to_s
      assigns(:elaboration).should eq(elaboration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Elaboration" do
        expect {
          post :create, :elaboration => valid_attributes
        }.to change(Elaboration, :count).by(1)
      end

      it "assigns a newly created elaboration as @elaboration" do
        post :create, :elaboration => valid_attributes
        assigns(:elaboration).should be_a(Elaboration)
        assigns(:elaboration).should be_persisted
      end

      it "redirects to the created elaboration" do
        post :create, :elaboration => valid_attributes
        response.should redirect_to(Elaboration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved elaboration as @elaboration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Elaboration.any_instance.stub(:save).and_return(false)
        post :create, :elaboration => {}
        assigns(:elaboration).should be_a_new(Elaboration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Elaboration.any_instance.stub(:save).and_return(false)
        post :create, :elaboration => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested elaboration" do
        elaboration = Elaboration.create! valid_attributes
        # Assuming there are no other elaborations in the database, this
        # specifies that the Elaboration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Elaboration.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => elaboration.id, :elaboration => {'these' => 'params'}
      end

      it "assigns the requested elaboration as @elaboration" do
        elaboration = Elaboration.create! valid_attributes
        put :update, :id => elaboration.id, :elaboration => valid_attributes
        assigns(:elaboration).should eq(elaboration)
      end

      it "redirects to the elaboration" do
        elaboration = Elaboration.create! valid_attributes
        put :update, :id => elaboration.id, :elaboration => valid_attributes
        response.should redirect_to(elaboration)
      end
    end

    describe "with invalid params" do
      it "assigns the elaboration as @elaboration" do
        elaboration = Elaboration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Elaboration.any_instance.stub(:save).and_return(false)
        put :update, :id => elaboration.id.to_s, :elaboration => {}
        assigns(:elaboration).should eq(elaboration)
      end

      it "re-renders the 'edit' template" do
        elaboration = Elaboration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Elaboration.any_instance.stub(:save).and_return(false)
        put :update, :id => elaboration.id.to_s, :elaboration => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested elaboration" do
      elaboration = Elaboration.create! valid_attributes
      expect {
        delete :destroy, :id => elaboration.id.to_s
      }.to change(Elaboration, :count).by(-1)
    end

    it "redirects to the elaborations list" do
      elaboration = Elaboration.create! valid_attributes
      delete :destroy, :id => elaboration.id.to_s
      response.should redirect_to(elaborations_url)
    end
  end

end
